name: "PRANC Training of CIFAR-10 with Resnet-20 with 1,000 alphas"
id: "R20_CIFAR10_PRANC_1000"
gpus: [0]

pranc:
  seed: 0 
  num_alpha: 1000
  window_size: 1000  

experiment:
  mode: 'train'   #[train, test]
  method: 'pranc'    #[normal, pranc]
  loss: "cross-entropy"   #[cross-entropy, mse]
  lr: 0.001
  epoch: 200
  batch_size: 256   #optional for testing
  # resume: 'R20_CIFAR_PRANC/pranc'  #for resuming training. if pranc, should be the signature path. if normal, should be the model path
  # load_model: 'R20_CIFAR_PRANC/pranc' #for testing 
  task: 'cifar10'
  model_arch: 'resnet20'

dataset:
  image_width: 32 # set 32 for cifar, 64 tiny, 256 for imagenet
  dataset_path: './datasets'

monitor:  #optional for testing
  log_rate: 50
  save_model: 'best_model.pt' 
  save_path: 'pranc'
