name: "PRANC Training of CIFAR-100 with Resnet-56 with 5,000 alphas"
id: "R56_CIFAR100_PRANC"
gpus: [3]

pranc:
  seed: 0 
  num_alpha: 5000
  window_size: 5000  
  lr: 0.0001

experiment:
  mode: 'train'   #[train, test]
  method: 'pranc'    #[normal, pranc]
  lr: 0.005
  epoch: 201
  batch_size: 256   #optional for testing
  resume: 'R56_CIFAR100_PRANC/pranc'  #for resuming training. if pranc, should be the signature path. if normal, should be the model path
  # load_model: 'R20_CIFAR_PRANC/pranc' #for testing 
  task: 'cifar100'
  model_arch: 'resnet56'

dataset:
  image_width: 32 # set 32 for cifar, 64 tiny, 256 for imagenet
  dataset_path: './datasets'

monitor:  #optional for testing
  log_rate: 50
  save_model: 'best_model.pt' 
  save_path: 'pranc'
