name: "PRANC Training of CIFAR-10 with AlexNet with 5,000 alphas"
id: "ALEX_CIFAR10_PRANC_5000"
gpus: [2]

pranc:
  seed: 0 
  num_alpha: 5000
  window_size: 5000  

experiment:
  mode: 'train'   #[train, test]
  method: 'pranc'    #[normal, pranc]
  loss: "cross-entropy"   #[cross-entropy, ]
  lr: 0.005
  epoch: 201
  batch_size: 256   #optional for testing
  # resume: 'R20_CIFAR_PRANC/pranc'  #for resuming training. if pranc, should be the signature path. if normal, should be the model path
  # load_model: 'R20_CIFAR_PRANC/pranc' #for testing 
  task: 'cifar10'
  model_arch: 'alexnet'

dataset:
  image_width: 32 # set 32 for cifar, 64 tiny, 256 for imagenet
  dataset_path: './datasets'

monitor:  #optional for testing
  log_rate: 50
  save_model: 'best_model.pt' 
  save_path: 'pranc'
