name: "PRANC Training of MNIST with LeNet with 400 alphas"
id: "LeNet_MNIST_PRANC"
gpus: [0]

pranc:
  seed: 0 
  num_alpha: 400
  window_size: 400  

experiment:
  mode: 'train'   #[train, test]
  method: 'pranc'    #[normal, pranc]
  loss: "cross-entropy"   #[cross-entropy, ]
  lr: 0.005
  epoch: 201
  batch_size: 256   #optional for testing
  # resume: 'LeNet_MNIST_PRANC/pranc'  #for resuming training. if pranc, should be the signature path. if normal, should be the model path
  # load_model: 'LeNet_MNIST_PRANC/pranc' #for testing 
  task: 'mnist'
  model_arch: 'lenet'

dataset:
  image_width: 28 # set 28 for mnist, 32 for cifar, 64 tiny, 256 for imagenet
  dataset_path: './datasets'

monitor:  #optional for testing
  log_rate: 50
  save_model: 'best_model.pt' 
  save_path: 'pranc'
