name: "PRANC on the fly Training of ImageNet with ResNet-18 with Single-GPU with 100,000 alpha"
id: "R18_IMAGENET_OTF_100,000"
gpus: [0,1,2,3]
port: 8880

pranc:
  seed: 0 
  num_alpha_enc: 2000
  num_alpha_cls: 60000

experiment:
  mode: 'train'   #[train, test]
  method: 'pranc_otf'   #[normal, pranc, pranc_bin, pranc_otf]
  loss: "cross-entropy"   #[cross-entropy, mse]
  lr: 0.0001
  optimizer: 'adam'  #[sgd, adam]
  # momentum: 0.9 #momentum for sgd
  # weight_decay: 0.0001 #weight decay for sgd
  scheduler: 'step' #[none, step, exponential]
  gamma: 0.5 #gamma for exponential and step scheduler 
  step: 100  #step for step scheduler
  epoch: 400
  batch_size: 512   #optional for testing
  # resume: 'R18_IMAGENET100_OTF_100,000/pranc'  #for resuming pranc training. 
  # resume: '<TASK_ID>/best_model.pt'  #for resuming normal training. 
  # load_model: '<TASK_ID>/pranc' #for pranc testing
  # load_model: '<TASK_ID>/best_model.pt' #for normal testing 
  task: 'imagenet' #[mnist, cifar10, cifar100, tiny, imagenet, imagenet100]
  model_arch: 'resnet18'  #[lenet, resnet18, resnet20, resnet56, alexnet, convnet]

dataset:
  image_width: 256 # set 28 for mnist, 32 for cifar, 64 tiny, 256 for imagenet
  dataset_path: '/datasets/imagenet'    #path to the dataset

monitor:  #optional for testing
  log_rate: 50
  save_model: 'best_model.pt'    #if touch, modify resume and load_model
  save_path: 'pranc'      #if touch, modify resume and load_model
